New Crowdin updates
zacharee/Tweaker pull request #17
Opened 2021-04-30 19:08 UTC by zacharee

2021-05-05 08:49 UTC, pablitoo3 approved these changes

2021-06-27 16:58 UTC, unrealperson666 approved these changes

2021-09-13 05:38 UTC, Myoazwan95 requested changes
![octocat-2x.png](https://user-images.githubusercontent.com/89642467/133029470-8c3da78a-87e9-47f2-9aa9-ed99db758d74.png)

2021-09-30 07:01 UTC, eyogl commented
Comienzo de cambios

2021-10-02 08:30 UTC, raminda2 approved these changes

2021-12-30 01:52 UTC, alaa12alaa reviewed
gh pr checkout 17

2023-04-06 01:32 UTC, merged